### ISSUE TITLE
run phpfmt failed

### ISSUE THREAD

**Issue by phuduc1193** [kokororin/vscode-phpfmt#37] opened 2018-05-24 16:00 UTC
Hi I just got this error recently. I'm not sure what I did wrong. Can you help me resolve it?
Please let me know what should I do to give you more information.

**Comment by Otavio-Parraga** [comment] 2018-05-24 19:03
I've got the same error in my vscode, already tried to fix it but nothing worked.

**Comment by kokororin** [comment] 2018-05-25 00:33
Cannot reproduced.
Delete folder `~/.vscode/extensions/kokororin.vscode-phpfmt-1.0.29` and reinstall may fixed.

**Comment by ivolvicente** [comment] 2018-05-25 10:04
I have the same problem, with last vscode version and windows 10.

I find that if my username and username folder have a least a space formatar fail.

In my case i have created a folder junction to test the comand in cmd, but it work to if the username folder get changed to "username~1" like its use as input file

![image](https://user-images.githubusercontent.com/11926387/40538730-5e2944c6-600a-11e8-8c4f-44b6df283300.png)

**Comment by kokororin** [comment] 2018-05-25 12:58
Can you confirm the problem on `1.0.30`?

**Comment by phuduc1193** [comment] 2018-05-25 14:03
Thank you it's no longer an issue for me.

**Comment by PrinceOfAbyss** [comment] 2024-04-20 01:04
This error is brought back in the last month. Currently on v1.1.39 and the issue started happening again. Any filename with a space in the filename (or parentheses) causes the same issue.

**Comment by kokororin** [comment] 2024-04-20 04:13
> This error is brought back in the last month. Currently on v1.1.39 and the issue started happening again. Any filename with a space in the filename (or parentheses) causes the same issue.

Thank you for reporting this issue. It should be resolved in version 1.1.40.

**Comment by PrinceOfAbyss** [comment] 2024-04-20 14:14
Thank you so much for the quick fix! I really appreciate it!

**Closed** 2024-04-21 00:05 UTC
