### ISSUE TITLE
adding "public" to closure and global functions causes syntax error

### ISSUE THREAD

**Issue by yinsee** [kokororin/vscode-phpfmt#125] opened 2023-11-02 07:47 UTC
```
Route::get('{path}', function  () {
    return redirect()->route('home');
})->where('path', '.*');
```

gets formatted to 
```
Route::get('{path}', public function  () {
    return redirect()->route('home');
})->where('path', '.*');
```

which causes syntax error.

**Comment by yinsee** [comment] 2023-11-02 07:48
similarly, 

```

function globaltest () {
    print ''. PHP_EOL;
}
```

becomes

```
public function globaltest () {
    print ''. PHP_EOL;
}
```

which also gives error when this is not a class method.

**Comment by driade** [comment] 2023-11-02 07:50
Hi, good morning. I can't reproduce with my config. Can you please share yours so I can see the transformers applied?

Thanks.

**Comment by yinsee** [comment] 2023-11-02 08:46
i am using phpfmt vscode extension v1.1.24

i only have this 2 turned on in settings

```
  "phpfmt.smart_linebreak_after_curly": true,
  "phpfmt.visibility_order": true,

```

**Comment by driade** [comment] 2023-11-02 10:34
I'm sorry I can't reproduce it. I'd suggest to remove the extension and reinstall it again, so we can be sure you've the latest version.

**Comment by driade** [comment] 2023-11-16 18:39
May you please execute "phpfmt > Open Output", then format the file, and paste here the command executed? Something like 

````
19:37:51.777 [INFO] Executing command: php "/Users/davidfernandez/.vscode/extensions/kokororin.vscode-phpfmt-1.1.24/node_modules/phpfmt/v2/fmt.stub.php" --indent_with_space=4 --visibility_order --smart_linebreak_after_curly "/var/folders/24/xvl5njxx7m1g94hsg7436knw0000gn/T/temp-qqfrym-a.php"
```

**Comment by d-enk** [comment] 2023-11-17 08:18
Its reproduced when file include class


```php

<?php

namespace Test;

function F()
{
}

class A
{
}
```

Executing command: php "/home/d-enk/.vscode/extensions/kokororin.vscode-phpfmt-1.1.27/node_modules/phpfmt/v2/fmt.stub.php" --psr2 --indent_with_space=4 --exclude=DoubleToSingleQuote,OrderAndRemoveUseClauses "/tmp/temp-haezevt-test.php"

**Comment by driade** [comment] 2023-11-18 08:31
Thanks @d-enk I've been able to reproduce the bug with your latest example.

**Comment by driade** [comment] 2023-11-18 08:41
Hello again, this should be already fixed. Please update to the latest version and kindly tell me if you find it fixed.

Thanks!

**Comment by driade** [comment] 2023-11-20 18:47
@yinsee may you please close the issue? Thanks!

**Comment by driade** [comment] 2023-12-02 15:44
@hellohasan sorry I can't reproduce the issue. Would you please share your config? Thanks.

**Comment by hellohasan** [comment] 2023-12-02 17:15
hello @driade 
this is my settings:
![image](https://github.com/kokororin/vscode-phpfmt/assets/24980053/2e9d2597-92d4-4a7d-aee8-101ecacb0b47)

**Comment by driade** [comment] 2023-12-02 17:31
@hellohasan thanks, would that be possible for you to paste it in text format?

**Comment by hellohasan** [comment] 2023-12-02 17:34
@driade 

```php

"phpfmt.passes": [
      "AlignDoubleArrow",
      "AlignDoubleSlashComments",
      "ShortArray",
      "MergeElseIf",
      "SpaceBetweenMethods",
      "AutoSemicolon",
      "GeneratePHPDoc",
      "IndentTernaryConditions",
      "ReplaceBooleanAndOr",
      "ReindentSwitchBlocks",
      "NewLineBeforeReturn",
      "OrderAndRemoveUseClauses",
      "SortUseNameSpace",
      "RemoveUseLeadingSlash"
  ],
  "phpfmt.exclude": [
      "AllmanStyleBraces",
      "StripNewlineWithinClassBody",
      "NewLineBeforeReturn"
  ],
  "phpfmt.psr2": true,

```

**Comment by hellohasan** [comment] 2023-12-02 17:42
@yinsee Hello sir, How did you fix your issue, I am also facing the same type of issue in laravel route.php file

**Comment by driade** [comment] 2024-03-08 21:05
Thank you @d-enk  this should be already fixed in the latest release. May you please confirm?

**Comment by driade** [comment] 2024-03-08 21:06
@hellohasan did you finally got why it was failing?

**Comment by driade** [comment] 2024-03-08 21:23
Hi again @hellohasan I was able to reproduce the error. It should now be fixed in the latest release. May you please confirm?

**Closed** 2024-04-25 04:57 UTC
