### ISSUE TITLE
Space after return type disappear in multi line argument list if first line of function is variable declaration.

### ISSUE THREAD

**Issue by Jipsukka** [kokororin/vscode-phpfmt#32] opened 2018-05-15 12:17 UTC
I use PSR2 standard and have similar function inside a class:
```
private function foobar(
    string $longVariableName,
    string $anotherLongVariableName,
    string $reallyLongVariableName,
    string $tooLongVariableNameSoThatLineLimitExeeds
): string {
    $foobar = 'asd';
    return $foobar;
}
```

Space between return type and curly bracers just gets deleted if I enable this extension.
If I do something else than declare variable, for example echo, if-statement, etc. space will stay like it should.

**Comment by kokororin** [comment] 2018-05-16 11:28
Fixed in 1.0.27

**Closed by kokororin** 2018-05-16 11:28 UTC

**Comment by mrTimofey** [comment] 2023-07-21 08:36
Same behavior in extension version 1.1.11 + PHP 8.1.2 + VSCode 1.80.1.

**Comment by driade** [comment] 2023-07-21 09:17
Hello @mrTimofey , I've just fixed this on

https://github.com/driade/phpfmt8/commit/a215a9a118b32b9a187449e6c87627865297255f

Please try upgrading via "phpfmt: Upgrade fmt.phar or fmt.stub.php" and let's see. Don't hesitate giving feedback as I'm not 100% sure this could lead to some side issues.

**Comment by mrTimofey** [comment] 2023-07-21 09:49
Yes, the issue is fixed after upgrading. Thank you for instant response :)

**Comment by driade** [comment] 2023-07-21 10:05
Thanks @mrTimofey The more samples of "bad code" you send, the easier for me to create patches.

**Comment by HeyMehedi** [comment] 2023-07-30 05:23
It's not working from my end. I am using v1.1.11

**Comment by driade** [comment] 2023-07-30 09:27
@HeyMehedi may you please post an example? Thanks.

**Comment by HeyMehedi** [comment] 2023-07-30 10:39
I am expecting this:
	```
protected function methodName(): void {

	}
```

but it's formatting this:

	```
protected function methodName(): void{

	}
```

**Comment by driade** [comment] 2023-07-31 06:43
@HeyMehedi I'm very sorry I'm unable to reproduce the bug. May you please share your configuration so I can use the exact options you're using?

Thanks.

**Comment by HeyMehedi** [comment] 2023-08-01 08:10
sorry, what would be the convenient way to reproduce from your end, please?

**Comment by driade** [comment] 2023-08-03 07:40
Please let me a few days until I figure it out. Thanks!

**Comment by driade** [comment] 2023-08-21 17:09
Sorry @HeyMehedi I can't figure it out...

**Comment by HeyMehedi** [comment] 2023-08-22 04:20
Hi @driade, Thanks for your help
Now I can see it's fixed 😄
